<html>
<head>
<?php
echo '<title>My First PHP Script</title>';
?>
</head>
<body>
<?php
       echo '<p>This content was generated by PHP</p>';
?>
<?php
?>
<form action="/submitUrl.php" method="post">
  <label for="imgUrl">Img Url:</label><br>
  <input type="text" name="imgUrl" id="imgUrl" placeholder="http Link">
  <input type="submit" value="Submit">
</form>
</body>
</html>
