<html>
<head>
<?php
echo '<title>My First PHP Script</title>';
?>
</head>
<body>
<?php
       echo '<p>This content was generated by PHP</p>';
?>
<?php

       $mySQL = new mysqli('localhost', 'root', 'Slu2023hello01', 'phpExample');

       $array = array();

       $query = "SELECT * FROM dogImgs;";

       echo "Reading data from database now. \n";
   
       $result = $mySQL->query($query);

       foreach ($result as $row) {
        array_push($array, $row['imgUrl']);
    }
?>
    <?php foreach($array as $value): ?>
        <img src="<?php echo $value; ?>" style="height: 100px; width 100px;"/>
    <?php endforeach; ?>
</body>
</html>
