<html>
<head>
<?php
echo '<title>My First PHP Script</title>';
?>
</head>
<body>
<?php
       echo '<p>This content was generated by PHP</p>';
?>
<?php 

$imgUrlFromForm = $_POST['imgUrl'];

echo "<p>writing $imgUrlFromForm to the database</p>";

$mySQL = new mysqli('localhost', 'root', 'Slu2023hello01', 'phpExample');

function writeRowToDatabase($tableName,$imgUrl) {
    global $mySQL;

    $query = "INSERT INTO $tableName (imgUrl) VALUES ('$imgUrl');";
    if ($mySQL->query($query) === TRUE) {
        echo "New record created successfully \r\n";
      } else {
        echo "Error: " . $query . "<br>" . $mySQL->error;
      }
}

writeRowToDatabase('dogImgs', $imgUrlFromForm);

echo "<p>wrote $imgUrlFromForm to the database</p>";

echo "<p>Sending you back to index in 5 secounds</p>";

?>

<script>
      function redirect () {
         setTimeout(myURL, 5000);
      }

      function myURL() {
        window.location.href = "index.php";
      }

      document.onload = redirect()
   </script>

</body>
</html>
